server:
  port: 8781

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#服务名称
spring:
  application:
    name: order-service

#自定义负载均衡策略 默认为轮询
#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#execution.isolation.thread.timeoutInMilliseconds

#ribbon请求超时设置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000

#hystrix超时时间-熔断
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

#redis链接
#redis:
#  database: 0
#  host: 127.0.0.1
#  port: 6379
#  timeout: 2000